create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
create table city (latitude float(53), longitude float(53), id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table clouds (cloudiness integer, id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table rain (rain1h float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
create table weather (feels_like float(53), humidity integer, pressure integer, temperature float(53), city_id bigint, id bigint not null auto_increment, description varchar(255), main varchar(255), primary key (id)) engine=InnoDB;
create table wind (direction integer, gust float(53), speed float(53), id bigint not null auto_increment, weather_id bigint, primary key (id)) engine=InnoDB;
alter table if exists clouds add constraint UKm5gwnj45qw94on34e4912xev8 unique (weather_id);
alter table if exists rain add constraint UKe8ulvwgem0ut9rkukiqhg9wej unique (weather_id);
alter table if exists wind add constraint UK6eu9t28k6rxxg3m8hb3leljxi unique (weather_id);
alter table if exists clouds add constraint FKs1t0naphf1mownvxg0frg86i foreign key (weather_id) references weather (id);
alter table if exists rain add constraint FKmt04the5b76vx932juhr0ik57 foreign key (weather_id) references weather (id);
alter table if exists weather add constraint FK43yufjhkj19nc6wlc6v5nm201 foreign key (city_id) references city (id);
alter table if exists wind add constraint FKnb45freup8g18offtdfhq8lt3 foreign key (weather_id) references weather (id);
