alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
alter table if exists clouds drop foreign key if exists FKs1t0naphf1mownvxg0frg86i;
alter table if exists rain drop foreign key if exists FKmt04the5b76vx932juhr0ik57;
alter table if exists weather drop foreign key if exists FK43yufjhkj19nc6wlc6v5nm201;
alter table if exists wind drop foreign key if exists FKnb45freup8g18offtdfhq8lt3;
drop table if exists city;
drop table if exists clouds;
drop table if exists rain;
drop table if exists weather;
drop table if exists wind;
